title = "Kollegenrunde"
baseURL = "https://kollegen.uber.space"
languageCode = "de-de"
theme = "ananke"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[de]
  title = "Kollegenrunde"

[taxonomies]
  category = "categories"
  tag = "tags"
  sport = "sports"
  eventtype = "eventtypes"
  member = "members"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

  
[params]
  sectionPagesMenu = "main"
  favicon = ""

  site_logo = ""
  description = "Der Kollege lädt ein, man trifft sich zum Radlen."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
#   TEST body_classes = "avenir bg-near-white"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  featured_image = "/images/070830-schatten.jpg"
  recent_posts_number = 5

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
